// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASgAA_lwdFiOtpKy67IiwMF_ZIN82-Pcs',
    appId: '1:536705162745:web:2262fa367eacffbc2e3128',
    messagingSenderId: '536705162745',
    projectId: 'stftmonitoring',
    authDomain: 'stftmonitoring.firebaseapp.com',
    databaseURL: 'https://stftmonitoring-default-rtdb.firebaseio.com',
    storageBucket: 'stftmonitoring.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLSqsPVwuj8keUB_sAYL8tJ4Bzy_t6alU',
    appId: '1:536705162745:android:846ac0427977f2882e3128',
    messagingSenderId: '536705162745',
    projectId: 'stftmonitoring',
    databaseURL: 'https://stftmonitoring-default-rtdb.firebaseio.com',
    storageBucket: 'stftmonitoring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdszmL1L0BldirykFNGDhdxnJJOQl5cM',
    appId: '1:536705162745:ios:bbb230b990ad1ab72e3128',
    messagingSenderId: '536705162745',
    projectId: 'stftmonitoring',
    databaseURL: 'https://stftmonitoring-default-rtdb.firebaseio.com',
    storageBucket: 'stftmonitoring.appspot.com',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdszmL1L0BldirykFNGDhdxnJJOQl5cM',
    appId: '1:536705162745:ios:bbb230b990ad1ab72e3128',
    messagingSenderId: '536705162745',
    projectId: 'stftmonitoring',
    databaseURL: 'https://stftmonitoring-default-rtdb.firebaseio.com',
    storageBucket: 'stftmonitoring.appspot.com',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASgAA_lwdFiOtpKy67IiwMF_ZIN82-Pcs',
    appId: '1:536705162745:web:750240045e69e9172e3128',
    messagingSenderId: '536705162745',
    projectId: 'stftmonitoring',
    authDomain: 'stftmonitoring.firebaseapp.com',
    databaseURL: 'https://stftmonitoring-default-rtdb.firebaseio.com',
    storageBucket: 'stftmonitoring.appspot.com',
  );
}
